version: "3.8"
services:
  postgres_hackernews:
    image: postgres:14
    environment:
      POSTGRES_DB: hackernews
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    container_name: postgres_hackernews
    volumes:
      - ./db-init/hacker_news.sql:/docker-entrypoint-initdb.d/hacker_news.sql
    networks:
      - microservices-network
    restart: always

  hacker_news:
    build: .
    container_name: hacker-news-web-crawler
    ports:
      - "8080:8080"
    depends_on:
      - postgres_hackernews
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_hackernews:5432/hackernews
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
